name: PartialBlocksTeleportationFix
version: "1.1"
main: fr.zcraft.PartialBlocksTPFix.PartialBlocksTeleportationFix
api-version: "1.13"

description: Fixes teleportation glitch on partial blocks (like paths or farmlands).
author: AmauryCarrade
